### ISSUE TITLE
Text is not properly aligned vertically.

### ISSUE THREAD

**Issue by Schoewilliam** [maweki/twitchlive-extension#1]
![capture du 2016-05-08 01-40-39](https://cloud.githubusercontent.com/assets/914451/15095254/e98470a8-14bd-11e6-926f-06644ffad9e2.png)

As you can see, the text is not properly aligned vertically. Not pretty :/.
Also, why not add an option to display/hide the text (icon-only)? 

Otherwise, keep up the good work! :+1:

**Comment by maweki** [comment]
You're right in both instances. Good idea.

**Comment by maweki** [comment]
I've got both issues fixed.

The vertical alignment is now centered

There's now an option to hide the streamer names and it only shows a number right to the icon of how many streamers are online. I thought this is better than just the icon, since you won't be able to see streamers coming online/going offline otherwise, if you're following a few streamers.

It might take a few days for the update to get through the review process, until you can use  extensions.gnome.org to update.

Also feel free to rate and review the extension on extensions.gnome.org.

**Comment by Schoewilliam** [comment]
Oh that's great! Thanks :)

**Comment by maweki** [comment]
@Schoewilliam please note that this fix, with other  great improvements, is now available at extensions.gnome.org
