### ISSUE TITLE
Notifications on channel going live

### ISSUE THREAD

**Issue by MedicMomcilo** [maweki/twitchlive-extension#38]
Configurable notifications for channels that goes live.
Preferably per-channel.

**Comment by RaphaelRochet** [comment]
I'm thinking about this for some time. With a action button on the notification to open the stream.
I could do that, if some users request it.

**Comment by maweki** [comment]
Configurable by channel might be a bit much. We could just have a checkbox in the settings but saving/loading and the streamer objects themselves, which are just the strings right now, would need to be reworked completely.

If this is implemented in general, there needs to be an option to disable/enable and it needs to start out as off by default.

**Comment by MedicMomcilo** [comment]
Yeah, I agree that it may be big change to allow per-streamer config. Perhaps somewhere in future with comma separated strings at first.

**Comment by GreyAsteroid** [comment]
This is the only feature keeping me from solely using this extension. I don't think this feature needs to be configurable by channel considering that streamers can actually be removed from the list though.

**Comment by KF5JWC** [comment]
I would like to take a stab at contributing a simple version of this because I want this too. (I only have use for a master off/on, so I would not add the per-streamer checkbox.)

What method should I use to create the notification?

I've looked at `Gio` first since it is already imported, however the docs mention that a `Gio.Notification` persists across reboots, which is probably undesired, and should only be used by *Applications* which can be activated by Dbus, which I don't think this extension qualifies for.

**Comment by KF5JWC** [comment]
Soooo *the whole shell* when I set up the notification and then call `.show()`. I need some advice or literature about how notifications work in gnome extensions if I'm going to be able to do this.

I am rather frustrated with the lack of apparent debug information, and the lack of docs in general, but especially about extensions and debugging (also that the extension-tool `--reload` doesn't actually reload the extension, meaning I have to restart the shell).
