### ISSUE TITLE
Extension errors on load

### ISSUE THREAD

**Issue by A-UNDERSCORE-D** [maweki/twitchlive-extension#51]
When loading the extension (via restarting gnome-shell) I get the following error in my log:
`Extension "TwitchLive_Panel@extensions.maweki.de" had error: TypeError: GObject.registerClass() used with invalid base class (is PanelMenuButton)`

Unsure what further information you may need for debug--Please let me know if you need anything else.

**Comment by A-UNDERSCORE-D** [comment]
Oh actually thinking about it. My system version should be here. This is what I get for writing bug reports when tired. I am using Ubuntu 18.04.2, on gnome version 3.28.3

**Comment by maweki** [comment]
We've updated the extension to be compatible with gnome-shell 3.32. The gnome devs broke compatibility at last and there is no way to support both 3.32 and earlier with the same codebase.

What you can and should do is checkout the 3.30-compat tag from the git repository (zip archive: https://github.com/maweki/twitchlive-extension/archive/3.30-compat.zip) and install it manually by extracting the archive to `.local/share/gnome-shell/extensions/TwitchLive_Panel@extensions.maweki.de/`

I am very sorry about the inconveniece but since gnome-shell disabled version checks since 3.26 (or something like that) and two years later just break the API, there's nothing we can do besides register two different extensions and I'm not sure this is the correct way to go.

**Comment by A-UNDERSCORE-D** [comment]
Ah Yeah I see. I misread the readme, my apologies for the erroneous Issue. Thank you for having a fix out as best as you can, and thank you for your work on the extension as a whole!

Hosting two copies of the extension may work, but that sounds like a mess to manage.
